name = "PopGen"
uuid = "af524d12-c74b-11e9-22a8-3b091653023f"
authors = ["Pavel Dimens", "Jason Selwyn"]
version = "0.0.1"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ECOS = "e2685f51-7e38-5353-a97d-a921fd2c8199"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GeneticVariation = "9bc6ac9d-e6b2-5f70-b0a8-242a01662520"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MultipleTesting = "f8716d33-7c4a-5097-896f-ce0ecbd3ef6b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CSV = "0.7"
DataFrames = "0.21"
Distributions = "0.23"
FileIO = "1.3"
GeneticVariation = "0.4"
JLD2 = "0.1"
MultipleTesting = "0.4"
StatsBase = "0.33"
julia = "1.3.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
