name = "PopGen"
uuid = "af524d12-c74b-11e9-22a8-3b091653023f"
authors = ["Pavel Dimens", "Jason Selwyn"]
version = "0.7.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
MultipleTesting = "f8716d33-7c4a-5097-896f-ce0ecbd3ef6b"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
PopGenCore = "45b36091-5ef7-4b08-b448-aaf24c763a14"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
DataFrames = "1.0, 1.1"
Distributions = "0.23, 0.24, 0.25"
MultipleTesting = "0.4, 0.5"
PooledArrays = "1.1"
ProgressMeter = "1.4"
Reexport = "1"
StatsBase = "0.33"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
